import { useMemo, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { Download, LockKeyhole, RefreshCw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getAdminState, lockAdmin, unlockAdmin } from "@/lib/afrostate/waitlist.functions";
import { brand } from "@/lib/afrostate/config";

type RecordItem = { id: string; full_name: string; phone_number: string; email: string | null; created_at: string };

type AdminState = { unlocked: boolean; records: RecordItem[] };

export function AdminDashboard({ initial }: { initial: AdminState }) {
  const unlock = useServerFn(unlockAdmin); const refresh = useServerFn(getAdminState); const lock = useServerFn(lockAdmin);
  const [data, setData] = useState(initial); const [query, setQuery] = useState(""); const [ascending, setAscending] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const records = data.unlocked ? data.records : [];
  const filtered = useMemo(() => [...records].filter((r) => `${r.full_name} ${r.phone_number} ${r.email ?? ""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => ascending ? a.created_at.localeCompare(b.created_at) : b.created_at.localeCompare(a.created_at)), [records, query, ascending]);

  async function handleUnlock(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { const code = String(new FormData(event.currentTarget).get("code") ?? ""); const result = await unlock({ data: { code } }); if (!result.ok) { setError("That access code didn't work."); return; } sessionStorage.setItem("afrostate-admin-token", result.token); const next = await refresh({ data: { token: result.token } }); if (!next.unlocked) { setError("Access was accepted, but the dashboard could not open. Try again."); return; } setData(next); } catch { setError("The dashboard could not open. Please try again."); } finally { setBusy(false); } }
  async function handleRefresh() { setBusy(true); const token = sessionStorage.getItem("afrostate-admin-token") ?? undefined; setData(await refresh({ data: { token } })); setBusy(false); }
  async function handleLock() { sessionStorage.removeItem("afrostate-admin-token"); await lock(); window.location.reload(); }
  function exportCsv() { const cell = (value: string) => `"${value.replaceAll('"', '""')}"`; const csv = ["Name,Phone,Email,Date joined", ...filtered.map((r) => [r.full_name,r.phone_number,r.email ?? "",new Date(r.created_at).toISOString()].map(cell).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href=url; a.download=`afrostate-waitlist-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url); }

  if (!data.unlocked) return <main className="grid min-h-screen place-items-center bg-secondary p-5"><form onSubmit={handleUnlock} className="w-full max-w-md border-4 border-foreground bg-primary p-8 shadow-[9px_9px_0_var(--foreground)]"><img src={brand.logo} alt="AFROSTATE" className="mb-8 w-40 border-2 border-foreground"/><LockKeyhole className="mb-4 size-10"/><h1 className="font-display text-5xl uppercase">Team access.</h1><p className="mt-3 font-bold">Enter the private access code to view signups.</p><Input name="code" type="password" autoComplete="current-password" required className="mt-7 h-12 rounded-none border-2 border-foreground bg-background" />{error && <p className="mt-3 text-sm font-bold text-destructive">{error}</p>}<Button variant="streetDark" size="lg" disabled={busy} className="mt-5 w-full">{busy ? "CHECKING..." : "ENTER DASHBOARD"}</Button></form></main>;

  const now = new Date(); const dayAgo = new Date(now.getTime()-86400000); const weekAgo = new Date(now.getTime()-604800000);
  const stats = [{ label:"TOTAL SIGNUPS", value:records.length },{ label:"TODAY", value:records.filter(r=>new Date(r.created_at)>=dayAgo).length },{ label:"THIS WEEK", value:records.filter(r=>new Date(r.created_at)>=weekAgo).length }];
  return <main className="min-h-screen bg-secondary"><header className="flex flex-wrap items-center justify-between gap-4 border-b-4 border-foreground bg-background px-5 py-4 md:px-8"><img src={brand.logo} alt="AFROSTATE" className="w-32 border-2 border-foreground"/><div className="flex gap-2"><Button variant="outline" onClick={handleRefresh} disabled={busy}><RefreshCw className={busy ? "animate-spin" : ""}/> REFRESH</Button><Button variant="streetDark" onClick={handleLock}><LockKeyhole/> LOCK</Button></div></header><div className="mx-auto max-w-[1500px] p-5 md:p-10"><p className="font-mono text-xs font-bold">INTERNAL / LIVE DATA</p><h1 className="mt-2 font-display text-5xl uppercase md:text-8xl">AFROSTATE / WAITLIST</h1><div className="mt-9 grid gap-4 sm:grid-cols-3">{stats.map(s=><div key={s.label} className="border-4 border-foreground bg-primary p-5 shadow-[5px_5px_0_var(--foreground)]"><p className="text-xs font-black">{s.label}</p><p className="font-display text-6xl">{s.value}</p></div>)}</div><div className="mt-10 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-5"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, phone or email" className="h-12 rounded-none border-2 border-foreground bg-background pl-10"/></div><Button variant="outline" size="lg" onClick={()=>setAscending(!ascending)}>{ascending ? "OLDEST FIRST" : "NEWEST FIRST"}</Button><Button variant="street" size="lg" onClick={exportCsv} disabled={!filtered.length}><Download/> EXPORT CSV</Button></div><div className="mt-6 border-4 border-foreground bg-background">{filtered.length ? <Table><TableHeader><TableRow className="bg-foreground hover:bg-foreground"><TableHead className="text-background">NAME</TableHead><TableHead className="text-background">PHONE</TableHead><TableHead className="text-background">EMAIL</TableHead><TableHead className="text-background">DATE JOINED</TableHead></TableRow></TableHeader><TableBody>{filtered.map(r=><TableRow key={r.id}><TableCell className="font-bold">{r.full_name}</TableCell><TableCell>{r.phone_number}</TableCell><TableCell>{r.email ?? "—"}</TableCell><TableCell>{new Intl.DateTimeFormat("en-NG",{dateStyle:"medium",timeStyle:"short"}).format(new Date(r.created_at))}</TableCell></TableRow>)}</TableBody></Table> : <div className="p-16 text-center"><p className="font-display text-5xl uppercase">The state is empty.</p><p className="mt-3 font-bold">No one has joined the waiting list yet.</p></div>}</div></div></main>;
}